const MOVIES_LIST_REQUEST = "MOVIES_LIST_REQUEST"
const MOVIES_LIST_SUCCESS = "MOVIES_LIST_SUCCESS"
const MOVIES_LIST_FAILURE = "MOVIES_LIST_FAILURE"
const MOVIES_ADD_REQUEST = "MOVIES_ADD_REQUEST"
const MOVIES_ADD_SUCCESS = "MOVIES_ADD_SUCCESS"
const MOVIES_ADD_FAILURE = "MOVIES_ADD_FAILURE"
const MOVIES_EDIT_REQUEST = "MOVIES_EDIT_REQUEST"
const MOVIES_EDIT_SUCCESS = "MOVIES_EDIT_SUCCESS"
const MOVIES_EDIT_FAILURE = "MOVIES_EDIT_FAILURE"
const MOVIES_DELETE_REQUEST = "MOVIES_DELETE_REQUEST"
const MOVIES_DELETE_SUCCESS = "MOVIES_DELETE_SUCCESS"
const MOVIES_DELETE_FAILURE = "MOVIES_DELETE_FAILURE"

const types = {
    MOVIES_LIST_REQUEST,
    MOVIES_LIST_SUCCESS,
    MOVIES_LIST_FAILURE,
    MOVIES_ADD_FAILURE,
    MOVIES_ADD_REQUEST,
    MOVIES_ADD_SUCCESS,
    MOVIES_DELETE_FAILURE,
    MOVIES_DELETE_REQUEST,
    MOVIES_DELETE_SUCCESS,
    MOVIES_EDIT_FAILURE,
    MOVIES_EDIT_REQUEST,
    MOVIES_EDIT_SUCCESS
}

export default types