const ACTORS_LIST_REQUEST = 'ACTORS_LIST_REQUEST'
const ACTORS_LIST_SUCCESS = 'ACTORS_LIST_SUCCESS'
const ACTORS_LIST_FAILURE = 'ACTORS_LIST_FAILURE'
const ACTORS_ADD_REQUEST = 'ACTORS_ADD_REQUEST'
const ACTORS_ADD_SUCCESS = 'ACTORS_ADD_SUCCESS'
const ACTORS_ADD_FAILURE = 'ACTORS_ADD_FAILURE'
const ACTORS_DELETE_REQUEST = 'ACTORS_DELETE_REQUEST'
const ACTORS_DELETE_SUCCESS = 'ACTORS_DELETE_SUCCESS'
const ACTORS_DELETE_FAILURE = 'ACTORS_DELETE_FAILURE'

const types = {
    ACTORS_LIST_REQUEST,
    ACTORS_LIST_SUCCESS,
    ACTORS_LIST_FAILURE,
    ACTORS_ADD_REQUEST,
    ACTORS_ADD_SUCCESS,
    ACTORS_ADD_FAILURE,
    ACTORS_DELETE_REQUEST,
    ACTORS_DELETE_SUCCESS,
    ACTORS_DELETE_FAILURE
}

export default types