apiVersion: apps/v1
kind: Deployment
metadata: 
  name: devapp
spec:
  selector:
    matchLabels:
      app: devapp

  replicas: 1
  template: 
    metadata:
      labels: 
        app: devapp
        
    spec:
     containers:
     - name: mybackend
       image: mybackend:1.0
       ports:
       - containerPort: 5000
       env: 
       - name: NODE_ENV
         value: "production"

     - name: mymongo
       image: mymongo:0.1
       ports:
       - containerPort: 27017
       volumeMounts:
       - mountPath: /data/db
         name: dev-volume

     - name: myredis
       image: myredis:0.1
       ports:
       - containerPort: 6379

     - name: myreact
       image: myreact:1.0
       ports:
       - containerPort: 3000
       env:
       - name: WDS_SOCKET_PORT
         value: "0"

     volumes:
     - name: dev-volume
       persistentVolumeClaim:
        claimName: dev-volume-claim