apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-volume
  labels:
    type: local
spec:
  storageClassName: dev-volume
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/usr/src/dev"