kind: Service
apiVersion: v1
metadata:
  name: backupservice
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 30200
  selector:
    app: testapp
  type: NodePort