apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp
spec:
  selector:
    matchLabels:
      app: testapp

  replicas: 1
  template: 
    metadata:
      labels: 
        app: testapp
        
    spec:
     containers:
     - name: mybackend:0.1
       image: ,ybackend:0.1
       ports:
       - containerPort: 5000

     - name: mymongo
       image: mymongo:0.1
       ports:
       - containerPort: 27017
       volumeMounts:
       - mountPath: /data/db
         name: app-volume

     - name: myredis
       image: myredis:0.1
       ports:
       - containerPort: 6379

     - name: myreact
       image: myreact:0.5
       ports:
       - containerPort: 3000
       env:
       - name: WDS_SOCKET_PORT
         value: "0"
       - name: REACT_APP_API_PORT
         value: "30500"

     volumes:
     - name: app-volume
       persistentVolumeClaim:
        claimName: app-volume-claim