apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: testbackend

  replicas: 1
  template: 
    metadata:
      labels: 
        app: testbackend
        
    spec:
     containers:
     - name: testbackend
       image: testbackend:0.1
       ports:
       - containerPort: 5000

     - name: mymongo
       image: mymongo:0.1
       ports:
       - containerPort: 27017

     - name: myredis
       image: myredis:0.1
       ports:
       - containerPort: 6379