apiVersion: apps/v1
kind: Deployment

metadata:
  name: mypgdep 
  labels:
    app: mypgdep

spec:
  template:
    metadata:
      name: mypostgres
      labels:
        app: mypostgres

    spec: 
      containers:
       - name: mypostgres
         image: postgres:alpine
         envFrom:
          - configMapRef:
             name: pg-config
          - secretRef:
             name: pgsecret
         volumeMounts:
          - name: pgvolume
            mountPath: /postgres
      volumes:
       - name: pgvolume
         persistentVolumeClaim:
          claimName: pg-volume-claim
                
  replicas: 1
  selector:
    matchLabels: 
      app: mypostgres