apiVersion: apps/v1
kind: Deployment

metadata:
  name: mypgdep 
  labels:
    app: mypgdep

spec:
  template:
    metadata:
      name: mypostgres
      labels:
        app: mypostgres


    spec: 
      containers:
        - name: mypostgres
          image: postgres:alpine
          env: 
          - name: POSTGRES_PASSWORD
            value: tajne
          - name: POSTGRES_DATABASE
            value: mydb
          - name: POSTGRES_USER
            value: backenduser
          - name: POSTGRES_HOST
            value: mypostgres
          - name: POSTGRES_PORT
            value: "5432"
                
  replicas: 1
  selector:
    matchLabels: 
      app: mypostgres