apiVersion: v1
kind: Pod
metadata:
  name: mypostgres
  labels:
    app: mypostgres
spec:
 containers:
  - name: postgres
    image: postgres:alpine
    env: 
    - name: POSTGRES_PASSWORD
      value: tajne
    - name: POSTGRES_DATABASE
      value: mydb
    - name: POSTGRES_USER
      value: backenduser
    - name: POSTGRES_HOST
      value: mypostgres
    - name: POSTGRES_PORT
      value: "5432"