apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-volume
  labels:
    type: local
spec:
  storageClassName: pg-volume
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/src/app"