kind: Service
apiVersion: v1
metadata:
  name: reactservice
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 30300
  selector:
    app: reactpod