const PERSONS_LIST_SUCCESS = 'PERSONS_LIST_SUCCESS'
const PERSONS_LIST_REQUEST = 'PERSONS_LIST_REQUEST'
const PERSONS_LIST_FAILURE = 'PERSONS_LIST_FAILURE'
const PERSONS_ADD_SUCCESS = 'PERSONS_ADD_SUCCESS'
const PERSONS_ADD_REQUEST = 'PERSONS_ADD_REQUEST'
const PERSONS_ADD_FAILURE = 'PERSONS_ADD_FAILURE'
const PERSONS_EDIT_SUCCESS = 'PERSONS_EDIT_SUCCESS'
const PERSONS_EDIT_REQUEST = 'PERSONS_EDIT_REQUEST'
const PERSONS_EDIT_FAILURE = 'PERSONS_EDIT_FAILURE'
const PERSONS_DELETE_SUCCESS = 'PERSONS_DELETE_SUCCESS'
const PERSONS_DELETE_REQUEST = 'PERSONS_DELETE_REQUEST'
const PERSONS_DELETE_FAILURE = 'PERSONS_DELETE_FAILURE'

const types = {
    PERSONS_LIST_SUCCESS,
    PERSONS_LIST_REQUEST,
    PERSONS_LIST_FAILURE,
    PERSONS_ADD_SUCCESS,
    PERSONS_ADD_REQUEST,
    PERSONS_ADD_FAILURE,
    PERSONS_EDIT_SUCCESS,
    PERSONS_EDIT_REQUEST,
    PERSONS_EDIT_FAILURE,
    PERSONS_DELETE_SUCCESS,
    PERSONS_DELETE_REQUEST,
    PERSONS_DELETE_FAILURE
}

export default types